<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $this->lang();
$valueLang = $filterLocale ? [$lang, ''] : null;
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$siteItemSets = $site->siteItemSets();

$query = $this->params()->fromQuery();
$headingTerm = $this->siteSetting('browse_heading_property_term');
$bodyTerm = $this->siteSetting('browse_body_property_term');
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>



<?php echo $this->pageTitle($translate('Item Sets'), 2); ?> 
<?php echo $this->searchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
<?php
foreach ($itemSets as $itemSet):
    $heading = $headingTerm ? $itemSet->value($headingTerm, ['default' => $translate('[Untitled]'), 'lang' => $valueLang]) : $itemSet->displayTitle(null, $valueLang);
    $body = $bodyTerm ? $itemSet->value($bodyTerm, ['lang' => $valueLang]) : $itemSet->displayDescription(null, $valueLang);
    $linkContent = '';
    if ($thumbnail = $this->thumbnail($itemSet, 'medium', ['class' => 'resource-thumbnail'])) {
        $linkContent .= $thumbnail;
    }
    $linkContent .= $heading;
    ?>
    <li class="item-set resource">
        <div class="resource-meta">
            <?php echo $itemSet->linkRaw($linkContent, null, ['class' => 'resource-title']); ?>
            <?php if ($body): ?>
            <div class="description"><?php echo $escape($body); ?></div>
            <?php endif; ?>
        </div>
    </li>
<?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>
