<?php
$escape = $this->plugin('escapeHtml');
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'item resource browse');
$siteItemSets = $site->siteItemSets();

$query = $this->params()->fromQuery();
$itemSetShow = isset($itemSet);
if ($itemSetShow):
    $this->htmlElement('body')->appendAttribute('class', 'item-set');
    $query['item_set_id'] = $itemSet->id();
endif;
$headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
$bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');
$sortHeadings = [
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title'
    ],
    [
        'label' => $translate('Identifier'),
        'value' => 'dcterms:identifier'
    ],
    [
        'label' => $translate('Created'),
        'value' => 'created'
    ],
];
?>


<?php if ($itemSetShow): ?>
    <?php echo $this->pageTitle('Collection', 2); ?>
    <?php echo $this->pageTitle($itemSet->displayTitle(), 3); ?>
<?php else: ?>
    <?php echo $this->pageTitle('Collection', 2); ?>
<?php endif; ?>

<?php echo $this->searchFilters(); ?>

<div class="collection-navigation">
    <?php foreach ($siteItemSets as $siteItemSet): ?>
        <?php $itemSet = $siteItemSet->itemSet(); ?>
        <?php $itemSetTitle = $itemSet->displayTitle(); ?>
        <?php echo $itemSet->link($itemSetTitle); ?>
    <?php endforeach; ?>    
    <?php echo $this->hyperlink('All', $this->url('site/resource', ['controller' => 'item', 'action' => 'browse'], [], true)); ?>
</div>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->hyperlink($translate('Advanced search'), $this->url('site/resource', ['controller' => 'item', 'action' => 'search'], ['query' => $query], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php $this->trigger('view.browse.before'); ?>
<ul class="resource-list">
<?php
foreach ($items as $item):
    $heading = $item->value($headingTerm, ['default' => $translate('[Untitled]')]);
    $body = $item->value($bodyTerm);
?>
    <li class="item resource">
        <?php if ($imageItem = $item->value('pwd:image')): ?>
        <?php $imageItemResource = $imageItem->valueResource(); ?>
        <?php $thumbnail = $this->thumbnail($imageItemResource, 'square'); ?>
        <?php echo $item->linkRaw($thumbnail, null, ['class' => 'item-thumbnail']); ?>
        <?php endif; ?>
        <div class="item-meta">
            <h4><?php echo $item->link($heading); ?></h4>
            <?php if ($body): ?>
            <div class="description"><?php echo $body; ?></div>
            <?php endif; ?>
        </div>
    </li>
<?php endforeach; ?>
</ul>
<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>
