<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.css', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/tablesaw/tablesaw.stackonly.jquery.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$title = $this->pageTitle($site->title());
$logo = $this->themeSettingAssetUrl('logo');
if ($logo):
    $title = '<img src="' . $this->escapeHtml($logo) . '">';
endif;
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <header class="site-header" role="banner">
            <div class="wrapper">
                <?php if ($this->themeSetting('logo')): ?>
                <a href="<?php echo $site->url(); ?>" class="site-title logo"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
                <?php else: ?>
                <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $site->title(); ?></a>
                <?php endif; ?>
    
                <nav class="site-nav">
                    <input type="checkbox" id="nav-trigger" class="nav-trigger" aria-label="<?php echo $this->translate('Toggle menu'); ?>"/>
                    <label for="nav-trigger">
                        <span class="menu-icon"></span>
                    </label>

                    <div class="trigger">
                    <?php
                    echo $site->publicNav()->menu()->renderMenu(null, [
                        'maxDepth' => $this->themeSetting('nav_depth') - 1
                    ]);
                    ?>
                    </div>
                </nav>
            </div>
        </header>
        <main class="page-content" aria-label="<?php echo $this->escapeHtml($this->translate('Content')); ?>">
            <div class="wrapper">
            <?php echo $this->content; ?>
            </div>
        </main>
        <footer class="site-footer h-card">
            <div class="wrapper">	
            	<p>Papers of the War Department is a project of the <a href="http://chnm.gmu.edu">Roy Rosenzweig Center for History and New Media</a>, <a href="http://www.gmu.edu">George Mason University</a> with funding from the <a href="http://www.archives.gov/nhprc/">National Historical Publications and Records Commission</a> and the <a href="http://www.neh.gov/">National Endowment for the Humanities</a>.</p>
            	<p>Descriptive metadata and transcriptions are available for use under the terms of the <a href="https://creativecommons.org/licenses/by/4.0/">Creative Commons by Attribution License (4.0)</a>. Permissions for use of the document images are held by their original repository.</p>
            	<div class="logos">
                	<a href="http://rrchnm.org" id="rrchnm-logo">RRCHNM</a>
                	<a href="https://www.acls.org/" id="acls-logo">ACLS</a>
                	<a href="http://www.archives.gov/nhprc/" id="nhrpc-logo">NHRPC</a>
                	<a href="http://www.neh.gov/" id="neh-logo">NEH</a>
            	</div>
            </div>
        </footer>
    </body>
</html>
